version: '3'

services:
  db:
    image: postgres
    restart: always
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: '12345678'
      POSTGRES_DB: customer_administration
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data